local player = game:GetService("Players").LocalPlayer
local virtualUser = game:GetService("VirtualUser")

player.Idled:Connect(function()
    virtualUser:Button2Down(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
    wait(1)
    virtualUser:Button2Up(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
end)
























































































































































-- obfuscated @ discord.gg/25ms, obfuscation: ib2 fork
return(function(...)local l,e,b=table,string,bit local a,f,B,r,i,N,P,M,h,o,A=e.byte,e.char,e.sub,l.concat,l.insert,math.ldexp,getfenv and getfenv()or _ENV,setmetatable,select,unpack or l.unpack,tonumber;local t=(function(c)local e,i,n,A,o,a,d=1,function(n)local e=""for A=1,#n,1 do e=e..f(a(n,A)-(11))end return A(e,36)end,"","",{},256,{}for e=0,a-1 do d[e]=f(e)end;local function t()local n=i(B(c,e,e))e=e+1;local A=i(B(c,e,e+n-1))e=e+n;return A end;n=f(t())o[1]=n;while e<#c do local e=t()if d[e]then A=d[e]else A=n..B(n,1,1)end;d[a]=n..B(A,1,1)o[#o+1],n,a=A,A,a+1 end;return l.concat(o)end)("=@@=>b=B@=>b=>V=BA=AN=Ab=Ab=B;=@a=B==AS=B<=Ac=AS=B>=Ab=>b=>a=BA=BQ=BS=BU=BW=>e=BA=B>=A_=AL=>b=A_=BD=BM=B;=B>=@==?U=?U=AR=AO=B>=AY=AM=B==AR=?T=CL=AD=?U=AW=B;=AO=?U=Ae=AS=AX=AN=AM=AM=AQ=B>=?U=@D=@?=@M=@A=@A=@B=@@=@B=@;=@C=@C=@<=@<=@B=@C=@L=@;=@L=@@=?U=@O=AP=@L=B;=@?=A@=?S=D<=AO=B;=A@=Ac=Ad=@d=@c=@M=AW=@c=@<=@a=@T=@W=@[=AS=AS=A_=@S=AN=AS=@[=@V=AO=@@=AS=AW=DA=@@=@d=@]=Ae=@W=B<=@[=Ac=@Q=@d=A@=AU=A`=AS=AP=B<=A@=@\\=@U=A>=@L=Ae=@C=BN=@A=AD=@R=A?=@C=>b=>^=BA=AU=AW=AD=AS=>b=>\\=BA=@Y=AS=Ab=AB=AS=B==Ad=AO=AY=MP=>]=BA=@R=C<=MW=MY=M[=MP=BY=B@=A?=AC=AW=A_=MX=B>=>b=?P=BA=@O=AW=B==AQ=MU=B;=N>=M\\=Mb=MZ=M\\=>b=?N=BA=A<=B>=MX=@S=AL=B;=Ac=MV=MX=NV=M]=BA=@N=AM=AY=AW=AC=N==N?=MX=MC=BA=@P=MN=MP=>`=NZ=N\\=B==@S=AR=>b=M^=B@=LD=B>=NR=N?=OM=MO=BB=BA=A;=AM=Ac=AY=AN=@W=AL=AW=AX=AC=AS=OU=OP=B@=@O=AM=AX=AO=P?=>b=>d=BA=A?=@]=MQ=BA=@[=AY=CL=Ac=AL=Ab=@[=AU=MP=>_=BA=B\\=B==Be=B_=B@=@P=?U=@[=BX=BA=PY=P[=Pc=PU=B@=BQ=AU=AO=AM=AL=O]=MP=MD=B@=AY=AO=Ab=Pd=BA=CC=B;=>b=P`=B@=B;=O>=AC=AC=>b=PB=>b=AS=AD=AX=P@=NB=Q^=>b=Ab=QW=PO=>X=MS=MU=A?=B==AM=AR=Oc=Ab=N^=AT=AM=Q?=N<=NS=AS=OT=Q]=Q@=AM=AC=CM=PQ=BA=Rd=Qd=BA=AW=Na=C[=B==OD=B@=P<=O^=?@=PR=NN=AW=AR=AM=A^=?^=@R=Ac=AX=?^=@[=CU=?^=CL=Qb=AS=AY=Ab=CM=S;=B@=AT=AO=AS=AC=AR=NB=>Z=OQ=MX=SC=P_=BA=Ad=O?=BT=Sa=>b=AO=AL=AC=TP=AS=>c=>c=TN=N[=N]=@V=>b=T>=B@=S_=BV=B==TP=AU=O_=OX=Q[=N>=A_=?^=QR=OV=BA=@V=AS=Nd=?^=A;=A_=B;=Ne=B@=PW=QA=Ab=SW=P^=R^=B@=?^=AR=N?=T==BA=@W=A^=S]=Na=S`=Rc=>b=@S=A?=RY=>b=@]=Ob=QB=Be=Qe=AA=AS=QN=QP=SA=V<=QW=QY=B@=@S=AB=Ue=N;=>b=@Y=ON=?^=@S=TZ=MR=B@=@T=AB=@Q=@P=P;=CL=AR=MP=Pe=>b=?Q=Rd=W;=Ba=Bc=>[=BA=AB=Bb=CT=N\\=?^=@b=>b=>W=QZ=B>=AQ=B==TQ=AY=Ra=B>=Ac=BQ=VM=@U=AA=@P=@N=TN=AT=AC=Ac=A^=Ac=NB=Qe=@X=Wd=X;=X==PV=B==M\\=X<=T[=XC=XL=B>=WO=UV=>b=Vd=AC=Ab=AW=XS=UA=XV=XX=RA=Vc=AS=A^=TN=V==Vd=XR=X]=SU=AO=X`=RA=@]=Y;=Y==BA=AL=AS=A`=W[=XS=@P=YD=YM=>Y=ML=MU=X_=U_=S_=WV=ON=NX=QZ=Vd=P[=AO=AT=N@=U^=AY=U`=S@=NY=B@=A<=AL=AQ=AL=AM=Ae=AL=?^=U]=YV=S`=Rd=PT=B@=?P=?O=BA=TV=B@=>`=?S=BA=OP=ZT=MC=?M=ZX=>b=TV=?P=?>=BA=Ub=WQ=Zb=BA=>^=Z\\=B@=@\\=Z^=NC=ZR=B@=W;=ZV=BA=BC=ZZ=[<=[M=[@=Z`=[;=Rd=WR=B@=Ub=[P=[>=[R=[B=XS=[L=ZP=[@=B@=[Y=NC=[R=Za=ZU=[U=Ze=[a=[==>b=[?=Z_=[\\=VU=[^=>b=??=[`=Z[=BA=\\N=Z_=[e=XN=BA=[V=PP=[;=\\?=\\A=[A=BA=WB=ZU=ZW=B@=?==\\O=[b=\\b=\\S=BA=V\\=B@=\\W=[X=\\Z=[[=BA=OW=Qd=\\`=>b=?Z=\\c=\\?=]O=];=B@=BC=\\V=\\==\\P=[Z=\\B=]V=\\_=BA=?X=]P=]]=[d=BA=RM=][=\\X=\\>=BA=\\[=ZQ=BA=YR=ZU=?]=BA=?T=[@=TV=[b=^D=^M=\\?=@D=]a=B@=Ye=]>=]W=[b=^==[\\=[\\=>`=^B=B@=B?=TV=^P=BA=^_=]X=>b=@<=]B=B@=[\\=>b=\\b=B@=ZZ=W<=Re=^;=]Y=\\\\=[_=]\\=B@=@Z=]_=_Q=_<=[c=BA=_@=\\O=_C=_D=^X=^S=_Z=^V=[W=Rd=Ub=ZZ=Qe=QD=>b=V^=V`=UA=X^=>b=W;=A<=B==Qc=?L=C;=BN=C?=?U=DY=?S=CT=AO=CP=AM=CR=AP=B>=VL=Qe=@O=MU=C[=OU=W;=@Y=@W=A;=VM=@\\=RR=Be=Rd=]c=B@=@A=_D=>b=?^=_D=_B=PQ=_B=[C=Ze=MB=`@=\\X=B_=aQ=B_=MD=RA=\\X=PQ=PQ=aC=aY=TN=Ze=PQ=_d=[N=[@=[b=ab=[b=WR=ZT=@M=]W=]e=\\O=VU=aR=Z;=`C=TN=`\\=Ab=`^=VM=A?=@Q=AB=`c=VU=@R=LN=Vd=B==NB=]U=V<=QP=Ab=AS=P[=?S=UL=UN=YZ=B@=CT=NR=M[=AW=RC=QP=?U=`X=VL=QT=\\@=a;=Re=b\\=\\U=aA=\\c=_a=\\O=Ye=^`=\\X=aQ=TV=PQ=W;=b@=TV=aQ=PQ=P`=OP=cV=OD=Zc=aZ=BA=cc=BY=Zc=_`=aN=\\O<T=BA=^>=_A=ZX=]M=MD=[O=\\?=dP=^d=b<=_N=b@=\\L=T>=dQ=BA=dY=dT=_U=[D=]M=dU=_L=Zd=]Z=aO=UW=`L=cT=[S=^M=dD=?W=\\X=RA=a\\=d;=OP=ND=OD=bB=_`=MD=PQ=eN=B_=eC=aO=B_=eM=B@=P`=T\\=W>=R^=eS=[a=XS=a\\=MD=MD=eM=Za=OP=\\^=B@=?D=OD=OP=e_=R^=eV><;C=S;=eN=BY=]==BA=P`=d>=aB=\\;=B_=M^=a\\=BY=OP=BC=a\\=T>=OP=WR=a\\=WB=OP=RM=a\\=MR=P`=YR=^\\=PU=?\\=^L=^d><<?=^a=B@=]^=];=MR=^U=[L=MR><<L=\\Y=]`><<C=>b=?Y=]a=MR=[\\=?^=`L=M^=eY=>d=BC=cP=B@=@L=Zd><<a=dc=b@=>b=a>=P`=aQ=RM=W==?C=>b><=@=>b><;?><=C><=L=`L><=O=B@=RM=Z\\><=R><===\\M=>b><=C=_d=@;><<@=[b><=\\><<U=?d=]B=YR=SL=ZU=B_=NY=cW=Pe=]O=_`=BA><>?=_D><>B=a>=>b=WB=YR=aM=B@=?`=>b=^@=[`><<W><><=_D=[\\=MD=a\\=ND=MD=?;=_V><=C><;D><=C><=C=?<=Rd=ND><=C=a[=[_=ND=BC=Ye=ZR=?B=[c=aQ=ZR=\\b=\\T=_V=[@=aQ=ND=?_=>b><>R><?A><;T=eN=[_><<e=W==aO=aQ=W=><?T=]O=Ye=W==?[=Q?><?^=>b><<?=^]=B@><=C><?]><@?=>b><?T=?V=_V><;?=eA=Re=`L=e\\=BA><;?=d;=Ye><=C><?d><;?=aQ><=C><@==Rd><;?><@A><=M><@C=>b=]^=Ye><;?><?d=WB=aQ><;?><@\\=BA=e<=aR=aQ=`L><?T><>V=B@=`L><?d=MR><AC><@<=>b><@>=>b=\\?=aT=B@=Z\\><?T=?R=_V=\\N><@O=Rd=SL=]D=\\Q=a]=eN=SL=]M><Ac=\\N=SL=Ye=Z\\><?d=\\N=aQ=Z\\><A?=B@=\\N><@_=\\N><?T=^D=Ye=\\N><?d=WR=aQ=\\N><BM=>b><=d><AB=B@=SL><?T=?U><;T=>b=?A><=W=W==Ye=SL><?d><Bd=aQ=SL><BZ><Bd><@_><Bd><?T=MB=a\\><?C=RM><;?=Ye><Bd><?d><?C=aQ><Bd><BZ><?C><@_><?C><?T=^R=a\\><>^=RM=`L=Ye><?C><?d><>^=aQ><?C><BZ><>^><@_><>^><?T><<c=a\\><>d><=T=be><>^><?d><>d=aQ><>^><BZ><>d><@_><>d><?T=b>=a\\=\\b=RM=\\N=Ye><>d><?d=\\b=aQ><>d><BZ=_X><AX=_?><@a=@?=_V=Za><A_=eN=aC><;D=aC=aC><DU=B@=Za><@U=\\a=>b><?d=Za=aQ=\\b><BZ=ND=\\e=be=ZR=?a=_V><?C=NY=ZR=TV=Ye=YR><Bd=NY=?^><A\\=NY=PQ=B?=U?=ND><>T=>b><L>=NY=ND=a`><@><]><=]=\\?><MQ><<U<S=]B=ZR><B\\=>`=B_><MN=[@><>>=cR><>B=_B><>B=^U><>M=>b=ZR><>P=c]=BA");local e,l,n,A=1,b and b.bxor or function(e,n)local A,l=1,0 while e>0 and n>0 do local B,d=e%2,n%2 if B~=d then l=l+A end e,n,A=(e-B)/2,(n-d)/2,A*2 end if e<n then e=n end while e>0 do local n=e%2 if n>0 then l=l+A end e,A=(e-n)/2,A*2 end return l end,140,function(A,e,n)if n then local e=(A/2^(e-1))%2^((n-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(A%(e+e)>=e)and 1 or 0;end;end local n,c,d=function()local a,d,B,A=a(t,e,e+3);a,d,B,A=l(a,n),l(d,n),l(B,n),l(A,n)e=e+4;return(A*16777216)+(B*65536)+(d*256)+a;end,function()local n=l(a(t,e,e),n);e=e+1;return n;end,function()local A,B=a(t,e,e+2);A,B=l(A,n),l(B,n)e=e+2;return(B*256)+A;end;local function R()local e=n();local n=n();local B=1;local l=(A(n,1,20)*(2^32))+e;local e=A(n,21,31);local n=((-1)^A(n,32));if(e==0)then if(l==0)then return n*0;else e=1;B=0;end;elseif(e==2047)then return(l==0)and(n*(1/0))or(n*(0/0));end;return N(n,e-1023)*(B+(l/(2^52)));end;local e,a=n,function(A)local d;if(not A)then A=n();if(A==0)then return'';end;end;d=B(t,e,e+A-1);e=e+A;local n={}for e=1,#d do n[e]=f(l(a(B(d,e,e)),140))end return r(n);end;local e,f=n,function(...)return{...},h('#',...)end local function b()local o,l,e={},{},{};local t={o,l,nil,e};local e,B=n(),{}for A=1,e do local n,e=c();if(n==1)then e=(c()~=0);elseif(n==2)then e=R();elseif(n==0)then e=a();end;B[A]=e;end;t[3]=c();for e=1,n()do l[e-1]=b();end;for t=1,n()do local e=c();if(A(e,1,1)==0)then local l,a,e=A(e,2,3),A(e,4,6),{d(),d(),nil,nil};if(l==0)then e[3]=d();e[4]=d();elseif(l==1)then e[3]=n();elseif(l==2)then e[3]=n()-(2^16)elseif(l==3)then e[3]=n()-(2^16)e[4]=d();end;if(A(a,1,1)==1)then e[2]=B[e[2]]end if(A(a,2,2)==1)then e[3]=B[e[3]]end if(A(a,3,3)==1)then e[4]=B[e[4]]end o[t]=e;end end;return t;end;local function c(e,a,d)local A,e,n=e[1],e[2],e[3];return function(...)local l,f,B,e,n,b,r,N,h,t,A=A,e,n,f,1,-1,{},{...},h('#',...)-1,{},{};for e=0,h do if(e>=B)then r[e-B]=N[e+1];else A[e]=N[e+1];end;end;local e=h-B+1 local e;local B;while true do e=l[n];B=e[1];if B<=27 then if B<=13 then if B<=6 then if B<=2 then if B<=0 then A[e[2]][e[3]]=A[e[4]];elseif B>1 then do return end;else A[e[2]][e[3]]=e[4];end;elseif B<=4 then if B==3 then local f=f[e[3]];local o;local B={};o=M({},{__index=function(n,e)local e=B[e];return e[1][e[2]];end,__newindex=function(A,e,n)local e=B[e]e[1][e[2]]=n;end;});for d=1,e[4]do n=n+1;local e=l[n];if e[1]==36 then B[d-1]={A,e[3]};else B[d-1]={a,e[3]};end;t[#t+1]=B;end;A[e[2]]=c(f,o,d);else local e=e[2]A[e]=A[e]()end;elseif B==5 then local n=e[2];local l=A[e[3]];A[n+1]=l;A[n]=l[e[4]];else A[e[2]][e[3]]=A[e[4]];end;elseif B<=9 then if B<=7 then local e=e[2]A[e]=A[e]()elseif B==8 then local B;A[e[2]]=a[e[3]];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]]=a[e[3]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]]=a[e[3]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];B=e[2]A[B](A[B+1])n=n+1;e=l[n];do return end;else local e=e[2]A[e](A[e+1])end;elseif B<=11 then if B==10 then A[e[2]]=a[e[3]];else A[e[2]]=A[e[3]];end;elseif B>12 then do return A[e[2]]end else A[e[2]]=c(f[e[3]],nil,d);end;elseif B<=20 then if B<=16 then if B<=14 then local l=e[3];local n=A[l]for e=l+1,e[4]do n=n..A[e];end;A[e[2]]=n;elseif B==15 then A[e[2]]=e[3];else A[e[2]]=A[e[3]][e[4]];end;elseif B<=18 then if B==17 then A[e[2]]=d[e[3]];else do return end;end;elseif B>19 then a[e[3]]=A[e[2]];else local e=e[2];do return o(A,e,b)end;end;elseif B<=23 then if B<=21 then local a;local B;B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];B=e[2];a=A[e[3]];A[B+1]=a;A[B]=a[e[4]];n=n+1;e=l[n];A[e[2]]=e[3];n=n+1;e=l[n];B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];elseif B>22 then n=e[3];else A[e[2]]=A[e[3]][e[4]];end;elseif B<=25 then if B>24 then A[e[2]]=a[e[3]];else A[e[2]][e[3]]=e[4];end;elseif B==26 then local n=e[2]A[n]=A[n](o(A,n+1,e[3]))else local n=e[2];local l=A[n];for e=n+1,e[3]do i(l,A[e])end;end;elseif B<=41 then if B<=34 then if B<=30 then if B<=28 then local e=e[2]A[e](A[e+1])elseif B==29 then do return A[e[2]]end else do return A[e[2]]();end;end;elseif B<=32 then if B==31 then A[e[2]]=e[3];else n=e[3];end;elseif B==33 then local l=e[3];local n=A[l]for e=l+1,e[4]do n=n..A[e];end;A[e[2]]=n;else A[e[2]]={};end;elseif B<=37 then if B<=35 then if not A[e[2]]then n=n+1;else n=e[3];end;elseif B==36 then A[e[2]]=A[e[3]];else local n=e[2];local l=A[n];for e=n+1,e[3]do i(l,A[e])end;end;elseif B<=39 then if B>38 then if not A[e[2]]then n=n+1;else n=e[3];end;else local f=f[e[3]];local o;local B={};o=M({},{__index=function(n,e)local e=B[e];return e[1][e[2]];end,__newindex=function(A,e,n)local e=B[e]e[1][e[2]]=n;end;});for d=1,e[4]do n=n+1;local e=l[n];if e[1]==36 then B[d-1]={A,e[3]};else B[d-1]={a,e[3]};end;t[#t+1]=B;end;A[e[2]]=c(f,o,d);end;elseif B==40 then local e=e[2];do return o(A,e,b)end;else local a;local B;A[e[2]]=d[e[3]];n=n+1;e=l[n];B=e[2];a=A[e[3]];A[B+1]=a;A[B]=a[e[4]];n=n+1;e=l[n];A[e[2]]=e[3];n=n+1;e=l[n];B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];B=e[2];a=A[e[3]];A[B+1]=a;A[B]=a[e[4]];n=n+1;e=l[n];A[e[2]]=e[3];n=n+1;e=l[n];B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];B=e[2];a=A[e[3]];A[B+1]=a;A[B]=a[e[4]];end;elseif B<=48 then if B<=44 then if B<=42 then local e=e[2]A[e]=A[e](A[e+1])elseif B==43 then local t;local c;local a;local B;A[e[2]]={};n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];B=e[2];a=A[e[3]];A[B+1]=a;A[B]=a[e[4]];n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];A[e[2]]=A[e[3]];n=n+1;e=l[n];B=e[2]A[B]=A[B](A[B+1])n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];A[e[2]]=A[e[3]];n=n+1;e=l[n];B=e[2]A[B]=A[B](A[B+1])n=n+1;e=l[n];A[e[2]]=e[3];n=n+1;e=l[n];a=e[3];c=A[a]for e=a+1,e[4]do c=c..A[e];end;A[e[2]]=c;n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];A[e[2]]=d[e[3]];n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];B=e[2]A[B]=A[B](A[B+1])n=n+1;e=l[n];A[e[2]][e[3]]=A[e[4]];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];B=e[2];t=A[B];for e=B+1,e[3]do i(t,A[e])end;else local l=e[2];local n=A[e[3]];A[l+1]=n;A[l]=n[e[4]];end;elseif B<=46 then if B==45 then if A[e[2]]then n=n+1;else n=e[3];end;else A[e[2]]={};end;elseif B>47 then A[e[2]]=c(f[e[3]],nil,d);else if A[e[2]]then n=n+1;else n=e[3];end;end;elseif B<=51 then if B<=49 then do return A[e[2]]();end;elseif B==50 then local B;A[e[2]]=A[e[3]];n=n+1;e=l[n];B=e[2]A[B]=A[B]()n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];if not A[e[2]]then n=n+1;else n=e[3];end;else a[e[3]]=A[e[2]];end;elseif B<=53 then if B==52 then local n=e[2]A[n]=A[n](o(A,n+1,e[3]))else local e=e[2]A[e]=A[e](A[e+1])end;elseif B>54 then A[e[2]]=d[e[3]];else local d;local B;A[e[2]]=a[e[3]];n=n+1;e=l[n];B=e[2];d=A[e[3]];A[B+1]=d;A[B]=d[e[4]];n=n+1;e=l[n];A[e[2]]=a[e[3]];n=n+1;e=l[n];A[e[2]]={};n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];A[e[2]][e[3]]=e[4];n=n+1;e=l[n];B=e[2]A[B]=A[B](A[B+1])n=n+1;e=l[n];A[e[2]]=A[e[3]][e[4]];n=n+1;e=l[n];B=e[2]A[B]=A[B](o(A,B+1,e[3]))n=n+1;e=l[n];if not A[e[2]]then n=n+1;else n=e[3];end;end;n=n+1;end;end;end;return c(b(),{},P)(...);end)(...)
